### ISSUE TITLE
How can I persistence the filter with redis ?

### ISSUE THREAD

**Issue by woorui** [linvon/cuckoo-filter#4]
I want persistence the cuckoo-filter for my distributed service, I would like to use redis. 

Can you give me any suggestion on my issue ?

thanks.

**Comment by linvon** [comment]
``` go
cf := cuckoo.NewFilter(4, 9, 3900, cuckoo.TableTypePacked)
b := cf.Encode()
redis.Set(your_key, b)

data := redis.Get(your_key)
newCf, _ := cuckoo.Decode(data)
```
Encode() return []byte slice represent your filter, you can save it on Redis.
Then you can get []byte data from Redis and use Decode(data) to rebuild your filter

**Comment by woorui** [comment]
https://github.com/woorui/cuckoo-filter-redis

Is this Wrapping ok ?

**Comment by linvon** [comment]
> https://github.com/woorui/cuckoo-filter-redis
> 
> Is this Wrapping ok ?

Looks ok

**Comment by woorui** [comment]
ok, many thanks
