### ISSUE TITLE
什么是半排序桶，我应该如何去理解，类比什么事物

### ISSUE THREAD

**Issue by GuoxinL** [linvon/cuckoo-filter#7]
什么是半排序桶，我应该如何去理解，类比什么事物

**Comment by linvon** [comment]
可以参考[实战指南](http://www.linvon.cn/posts/%E5%B8%83%E8%B0%B7%E9%B8%9F%E8%BF%87%E6%BB%A4%E5%99%A8%E5%AE%9E%E6%88%98%E6%8C%87%E5%8D%97/#%e4%b8%80%e4%ba%9b%e8%bf%9b%e9%98%b6%e8%a7%a3%e9%87%8a)中提到的第二点解释
半排序是将原来桶中可能存储的内容值的所有情况做了枚举后，按照排列组合顺序排序。这样只需要在桶中存储对应值的序号而不用存储具体的值。在一定场景下存储序号可以比存储值少占用一个bit，类似于存储了一个索引

**Comment by GuoxinL** [comment]
![image](https://user-images.githubusercontent.com/19989609/162189333-7d2f2824-78c4-40a5-bb60-2214b754a316.png)
您的指南挺清晰的，在调优方面解决了当下的问题。
before
![image](https://user-images.githubusercontent.com/19989609/162189513-b949065b-4fa1-4d35-ab6d-b5d62bd36cf8.png)
after
![image](https://user-images.githubusercontent.com/19989609/162189558-569736bd-f571-4be1-a4ec-21365eabe20a.png)
但是我仍然有一个问题，指南中提到的负载因子是如何得来的，为什么size的大小要遵循这个公式size/α ~=(<) 2^n

**Comment by linvon** [comment]
1. 负载因子是当达到这个阈值时插入成功率会急剧劣化，这个受影响于hash算法与过滤器的设计，具体数值的来源都是由原论文作者经过实验得出的
2. 桶的大小必须满足为2的指数倍，因此size/α代表的真正存储的数量级应该小于且无限接近桶大小，否则就算比当前桶大小大了1，那也需要将桶大小翻倍才能存储这些数据，会造成很多不必要的空间浪费

**Comment by GuoxinL** [comment]
感谢作者的回复

**Comment by GuoxinL** [comment]
计算假阳性概率的公式是`2b/2^f< r`但是假阳性的概率不是随着过滤器的项增多，假阳性的概率不断的增大；这个公式计算的是什么时候的假阳性概率

**Comment by linvon** [comment]
假阳性率本质上是通过hash计算后位置冲突的概率，这与过滤器本身的属性有关，与已插入的项数无关。你所描述的应该是插入时产生错误冲突的概率，这个概率应该在桶满时等于假阳性率

**Comment by GuoxinL** [comment]
感谢您的回复

**Comment by GuoxinL** [comment]
感谢您的回复
